config/routes.rb
Rails.application.routes.draw do
get '/blogs' => 'blog#index'
get '/blogs/new' => 'blog#new', as: 'new_blog'
get '/blogs/:id' => 'blog#show', as: 'blog'
post 'blogs' => 'blog#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
        @blogs = Blog.all
    end

    def show
        @blog = Blog.find(params[:id])
    end

    def new
        @blog = Blog.new
    end

    def create
        @blog = Blog.create(blog_params)
        if @blog.valid?
            redirect_to blog_path
        end
    end

    private
    def blog_params
        params.require(:blog).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/index.html.erb
<h1>All Blog Posts</h1>
<ul>
  <% @blogs.each do |blog| %>
    <li>
      <%= link_to blog.title, blog_path(blog) %>
    </li>
  <% end %>
</ul>

<p><%= link_to 'Add New Blog', new_blog_path %></p>

app/views/blog/new.html.erb
<h2>Add a new blog:</h2>

<%= form_with model: @blog do |form|%>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :content %>
  <%= form.text_field :content %>
  <%= form.submit "Submit" %>
<% end %>

<%= link_to 'Back to All Posts', blogs_path %>

app/views/blog/show.html.erb
<h1><%= @blog.title %></h1>
<p><%= @blog.content %></p>

<%= link_to 'Back to All Posts', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>